theme: jekyll-theme-midnight
title: Ring 0x00
description: A blog about information security, networking and technology. By Iliya Dafchev.
baseurl: ""
url: https://idafchev.github.io
show_downloads: false
github_username:  idafchev
#highlighter: rouge
gems:
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
