theme: jekyll-theme-midnight
title: Ring 0x00
description: One ring to rule them all
baseurl: ""
url: https://idafchev.github.io
show_downloads: false
github_username:  idafchev
#highlighter: rouge
gems:
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
