theme: jekyll-theme-midnight
title: Ring 0x00
description: A blog about information security, networking and technology. By Iliya Dafchev.
baseurl: ""
url: "https://idafchev.github.io"
show_downloads: false
google_verify: cW4TLH1bfeLvBJnTMoroLoGm6POKJdKgoyIgt8hQHfI
github_username:  idafchev
#highlighter: rouge
gems:
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
